version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run: echo "Hello worl"
  build:
    docker:
      - iamge: circleci/python:3.7.1
    steps:
      - checkout
      - run: echo "Hello world"
