version: 2
jobs:
  one:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run: echo "A first hello"
  two:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run: echo "A more familiar hi"
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two